// Mocks generated by Mockito 5.0.15 from annotations
// in rental/test/features/property/bloc/add_review/add_review_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rental/core/models/review.dart' as _i3;
import 'package:rental/features/property/data_provider/add_review/review_remote_data_provider.dart'
    as _i2;
import 'package:rental/features/property/repository/add_review/add_review_repository.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeReviewRemoteDataProvider_0 extends _i1.Fake
    implements _i2.ReviewRemoteDataProvider {}

class _FakeReview_1 extends _i1.Fake implements _i3.Review {}

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i4.ReviewRepository {
  MockReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReviewRemoteDataProvider get reviewRemoteDataProvider =>
      (super.noSuchMethod(Invocation.getter(#reviewRemoteDataProvider),
              returnValue: _FakeReviewRemoteDataProvider_0())
          as _i2.ReviewRemoteDataProvider);
  @override
  _i5.Future<List<_i3.Review>> getReviewsFromRemote(String? id) =>
      (super.noSuchMethod(Invocation.method(#getReviewsFromRemote, [id]),
              returnValue: Future<List<_i3.Review>>.value(<_i3.Review>[]))
          as _i5.Future<List<_i3.Review>>);
  @override
  _i5.Future<_i3.Review> createRemoteReview(
          {_i3.Review? review, String? propertyId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#createRemoteReview, [],
                  {#review: review, #propertyId: propertyId, #token: token}),
              returnValue: Future<_i3.Review>.value(_FakeReview_1()))
          as _i5.Future<_i3.Review>);
  @override
  _i5.Future<_i3.Review> updateRemoteReview(
          {_i3.Review? review, String? propertyId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#updateRemoteReview, [],
                  {#review: review, #propertyId: propertyId, #token: token}),
              returnValue: Future<_i3.Review>.value(_FakeReview_1()))
          as _i5.Future<_i3.Review>);
  @override
  _i5.Future<_i3.Review> getRemoteReview({String? propertyId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#getRemoteReview, [],
                  {#propertyId: propertyId, #token: token}),
              returnValue: Future<_i3.Review>.value(_FakeReview_1()))
          as _i5.Future<_i3.Review>);
  @override
  String toString() => super.toString();
}
