// Mocks generated by Mockito 5.0.15 from annotations
// in rental/test/features/user/bloc/profile_bloc/profile_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rental/core/models/user.dart' as _i2;
import 'package:rental/features/user/repository/user_repository.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUser_0 extends _i1.Fake implements _i2.User {}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> updateUser({_i2.User? user, String? newProfilePath}) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateUser, [], {#user: user, #newProfilePath: newProfilePath}),
          returnValue:
              Future<_i2.User>.value(_FakeUser_0())) as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> getCurrentUser(String? token) =>
      (super.noSuchMethod(Invocation.method(#getCurrentUser, [token]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<bool> deleteUser() =>
      (super.noSuchMethod(Invocation.method(#deleteUser, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}
